version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    ignore:
    # these need to be updated together, so dependabot PRs 
    # are just noise. So, ignore them:
    - package-name: sp-core
    - package-name: sp-keyring
    - package-name: sp-runtime
    - package-name: sp-core-hashing
    - package-name: sp-version
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
