[workspace]

members = [
    "cli",
    "codegen",
    "examples",
    "testing/test-runtime",
    "testing/integration-tests",
    "testing/ui-tests",
    "macro",
    "metadata",
    "subxt",
    "wasm-tests",
]

resolver = "2"
