[workspace]

members = [
    "cli",
    "codegen",
    "examples",
    "integration-tests",
    "macro",
    "metadata",
    "subxt",
    "test-runtime"
]

[patch.crates-io]
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }