[workspace]

members = [
    "cli",
    "codegen",
    "examples",
    "testing/test-runtime",
    "testing/integration-tests",
    "testing/ui-tests",
    "macro",
    "metadata",
    "subxt",
    "wasm-tests",
]

resolver = "2"

[patch.crates-io]
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", branch = "na-async-wasm-feature" }
