[workspace]

members = [
    "cli",
    "codegen",
    "examples",
    "testing/test-runtime",
    "testing/integration-tests",
    "testing/ui-tests",
    "testing/wasm-tests",
    "macro",
    "metadata",
    "subxt"
]

resolver = "2"
