[package]
name = "test-runtime"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
subxt = { workspace = true, features = ["default"] }

[build-dependencies]
substrate-runner = { workspace = true }
impl-serde = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
which = { workspace = true }
jsonrpsee = { workspace = true, features = ["async-client", "client-ws-transport"] }
