[package]
name = "test-runtime"
version = "0.28.0"
edition = "2021"
publish = false

[dependencies]
subxt = { path = "../../subxt" }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive", "full"] }

[build-dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive", "full"] }
substrate-runner = { path = "../substrate-runner" }
impl-serde = "0.4.0"
serde = "1.0.160"
tokio = { version = "1.27", features = ["macros", "rt-multi-thread"] }
which = "4.4.0"
jsonrpsee = { version = "0.16.0", features = ["async-client", "client-ws-transport"] }
hex = "0.4.3"
