[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
tracing-wasm = { workspace = true }
console_error_panic_hook = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true, default-features = false, features = ["jsonrpsee-web"] }
