[package]
name = "test-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { path = ".." }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate/", branch = "master" }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }

[build-dependencies]
hex = "0.4.3"
subxt = { path = ".." }
ureq = { version = "2", features = ["json"] }