[package]
name = "subxt-examples"
version = "0.27.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
description = "Subxt example usage"

[dev-dependencies]
subxt = { path = "../subxt" }
tokio = { version = "1.25", features = ["rt-multi-thread", "macros", "time"] }
sp-keyring = "20.0.0"
futures = "0.3.26"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
hex = "0.4.3"
tracing-subscriber = "0.3.11"
sp-core = { version = "18.0.0", default-features = false }
sp-runtime = "20.0.0"
