[package]
name = "test-node"
version = "2.0.0-rc3"
authors = ["Anonymous"]
description = "Substrate Node template"
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"

sc-cli = { version = "0.8.0-rc3", features = ["wasmtime"] }
sp-core = { version = "2.0.0-rc3" }
sc-executor = { version = "0.8.0-rc3", features = ["wasmtime"] }
sc-service = { version = "0.8.0-rc3", features = ["wasmtime"] }
sp-inherents = { version = "2.0.0-rc3" }
sc-transaction-pool = { version = "2.0.0-rc3" }
sp-transaction-pool = { version = "2.0.0-rc3" }
sc-network = { version = "0.8.0-rc3" }
sc-consensus-aura = { version = "0.8.0-rc3" }
sp-consensus-aura = { version = "0.8.0-rc3" }
sp-consensus = { version = "0.8.0-rc3" }
sc-consensus = { version = "0.8.0-rc3" }
sc-finality-grandpa = { version = "0.8.0-rc3" }
sp-finality-grandpa = { version = "2.0.0-rc3" }
sc-client-api = { version = "2.0.0-rc3" }
sp-runtime = { version = "2.0.0-rc3" }
sc-basic-authorship = { version = "0.8.0-rc3" }

test-node-runtime = { version = "2.0.0-rc3", path = "runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0-rc3" }
