name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: |
        rustup install nightly --profile default

    - name: fmt
      run: cargo +nightly fmt --all -- --check

    - name: build
      run: cargo build --verbose

    - name: test
      run: cargo test --verbose
